server:
  port: 9092
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/ 
spring:
  application:
    name: SHOPPING-SERVICE
